// SLURPSLOP Data module
// All filter data bundled directly in the script
(() => {
  const NS = (window.SlurpSlop = window.SlurpSlop || {});
  // TODO: Need to do a full review of these lists (mainly selectors), particularly as a lot of them are client-dependent
  // and may change dependent on google updates / obfuscation
  const adIndicatorLabels = [
    'sponsored',
    'ads',
    'advertisement',
    'shopping results',
    'shop deals',
    'shop ads',
    'promoted'
  ];

  const adSelectors = [
    '[data-text-ad]',
    'div.uEierd',
    'div[data-veid*="ads"]',
    'div[data-sokoban-feature="shopping_ads"]',
    'div.cu-container',
    'div[aria-label="Ads"]',
    'div[aria-label="Ads results"]',
    'div[aria-label="Sponsored"]',
    'div[class*="commercial-unit-desktop"]',
    'div[class*="commercial-unit-mobile"]'
  ];

  const aiIndicatorPhrases = [
    'ai overview',
    'overview from google',
    'google ai overview',
    'overview generated by ai',
    'generated by ai',
    'ai-generated answer',
    'ai-generated content',
    'ai-generated summary',
    'ai summary',
    'google generative ai',
    'generative ai answer'
  ];

  const aiOverviewPatterns = [
    'übersicht mit ki',
    'ai overview',
    'prezentare generală generată de ai',
    'ai による概要',
    'обзор от ии',
    'ai 摘要',
    'ai-overzicht',
    'vista creada con ia',
    'přehled od ai'
  ];

  const aiSelectors = [
    'div.YzCcne[data-mcpr][data-mcp]',
    'div[data-mg-cp="YzCcne"]',
    'div[data-attrid^="SrpGenSum"]',
    'div[jscontroller="EYwa3d"]',
    'div[jscontroller="qwbW4b"]',
    'div[jscontroller="i8S0p"]',
    'g-section-with-header:has(div.lLGV5d)',
    'div.JJSijf',
    'div.aeJESe',
    'div[data-attrid*="ai_generated"]',
    'div[data-sokoban-feature="ai_generated"]',
    'div.xvfwl',
    'div.ULMdaf',
    'div.hlcw0c > g-section-with-header',
    'div.ETsHvc',
    'g-card',
    'div[data-md*="structured_snippet"]',
    'div[data-ved][data-hveid][jscontroller="zdw0yd"]',
    'div[jscontroller="EEh6s"]',
    'div[jscontroller="sYACre"]',
    'div[jscontroller="CnRgdd"]',
    'div[jscontroller="Elkdbc"]'
  ];

  const disableTerms = [
    'ai overview',
    'sparknotes',
    'generative ai',
    'content farms',
    'filter google search',
    'remove ai results',
    'block ai overview',
    'ai'
  ];

  const lowQualityDomains = [
    'sparknotes',
    'litcharts',
    'shmoop',
    'cliffsnotes',
    'coursehero',
    'study.com',
    'gauth',
    'bartleby',
    'slader',
    'studylib',
    'gradeup',
    'gradesaver',
    'chegg',
    'brainly',
    'scribd',
    '123helpme',
    'megaessays',
    'bookrags',
    'papersowl',
    'studymode',
    'superprof',
    'edubirdie',
    'academized',
    'essaypro',
    'essayhub',
    'scribbr'
  ];

  // Export data to namespace, objects should exist already
  Object.assign(NS, {
    filterData: {
      adIndicatorLabels,
      adSelectors,
      aiIndicatorPhrases,
      aiOverviewPatterns,
      aiSelectors,
      disableTerms,
      lowQualityDomains
    }
  });
})();
