// SlopSlurp: Professional Search Results
// This content script removes AI Overview sections and low-quality content from Google search results
// Now supports both comprehensive and minimalist modes

(function() {
  'use strict';

  // ============ CORE VARIABLES ============

  let extensionEnabled = true;
  let lastQuery = '';
  let minimalistObserver = null;
  let comprehensiveObserver = null;

  let currentStats = {
    aiElementsRemoved: 0,
    lowQualitySitesRemoved: 0,
    adsRemoved: 0,
    totalElementsRemoved: 0,
    scanCount: 0,
    lastScanTime: 0,
    placeholdersCreated: 0
  };

  // Logging toggle for verbose console output
  let loggingEnabled = false;

  let filterSettings = {
    removeAiOverview: true,
    removeLowQualitySites: true,
    removeAds: true,
    academicMode: false,
    minimalistMode: false,
    hideAiModeButton: true,
    showReplacementPlaceholders: false,
    customWhitelist: []
  };

  const DEFAULT_FILTER_DATA = Object.freeze({
    disableTerms: [
      'ai overview',
      'sparknotes',
      'generative ai',
      'content farms',
      'filter google search',
      'remove ai results',
      'block ai overview'
    ],
    aiOverviewPatterns: [
      'übersicht mit ki',
      'ai overview',
      'prezentare generală generată de ai',
      'ai による概要',
      'обзор от ии',
      'ai 摘要',
      'ai-overzicht',
      'vista creada con ia',
      'přehled od ai'
    ],
    aiSelectors: [
      'g-section-with-header:has(div.lLGV5d)',
      'div.JJSijf',
      'div.aeJESe',
      'div[data-attrid*="ai_generated"]',
      'div[data-sokoban-feature="ai_generated"]',
      'div.xvfwl',
      'div.ULMdaf',
      'div.hlcw0c > g-section-with-header',
      'div.ETsHvc',
      'g-card',
      'div[data-md*="structured_snippet"]',
      'div[data-ved][data-hveid][jscontroller="zdw0yd"]',
      'div[jscontroller="EEh6s"]'
    ],
    aiIndicatorPhrases: [
      'ai overview',
      'overview from google',
      'google ai overview',
      'overview generated by ai',
      'generated by ai',
      'ai-generated answer',
      'ai-generated content',
      'ai-generated summary',
      'ai summary',
      'google\'s ai summary',
      'google generative ai',
      'generative ai answer'
    ],
    lowQualityDomains: [
      'sparknotes.com',
      'www.sparknotes.com',
      'litcharts.com',
      'www.litcharts.com',
      'shmoop.com',
      'www.shmoop.com',
      'cliffsnotes.com',
      'www.cliffsnotes.com',
      'coursehero.com',
      'www.coursehero.com',
      'study.com',
      'www.study.com'
    ],
    adSelectors: [
      '[data-text-ad]',
      'div.uEierd',
      'div[data-veid*="ads"]',
      'div[data-sokoban-feature="shopping_ads"]',
      'div.cu-container',
      'div[aria-label="Ads"]',
      'div[aria-label="Ads results"]',
      'div[aria-label="Sponsored"]',
      'div[class*="commercial-unit-desktop"]',
      'div[class*="commercial-unit-mobile"]',
      'div[jscontroller="sYACre"]',
      'div[jscontroller="CnRgdd"]'
    ],
    adIndicatorLabels: [
      'sponsored',
      'ads',
      'advertisement',
      'shopping results',
      'shop deals',
      'shop ads',
      'promoted'
    ]
  });

  const DATA_FILE_PATHS = {
    disableTerms: 'data/disable_terms.json',
    aiOverviewPatterns: 'data/ai_overview_patterns.json',
    aiSelectors: 'data/ai_selectors.json',
    aiIndicatorPhrases: 'data/ai_indicator_phrases.json',
    lowQualityDomains: 'data/low_quality_domains.json',
    adSelectors: 'data/ad_selectors.json',
    adIndicatorLabels: 'data/ad_indicator_labels.json'
  };

  let filterData = cloneDefaultData();
  let filterDataLoaded = false;
  let filterDataLoadingPromise = null;

  const PLACEHOLDER_TIMEOUT_MS = 15000;
  const placeholderEntries = new Map();
  let placeholderIdCounter = 0;
  let placeholderStylesInjected = false;

  // ============ UTILITY FUNCTIONS ============

  // Simple logger
  const Logger = {
    info: (msg, data) => {
      if (!loggingEnabled) {
        return;
      }
      console.log(`[SlopSlurp] INFO: ${msg}`, data || '');
    },
    warn: (msg, data) => console.warn(`[SlopSlurp] WARN: ${msg}`, data || ''),
    error: (msg, data) => console.error(`[SlopSlurp] ERROR: ${msg}`, data || ''),
    debug: (msg, data) => {
      if (!loggingEnabled) {
        return;
      }
      console.log(`[SlopSlurp] DEBUG: ${msg}`, data || '');
    }
  };

  function unique(values) {
    return [...new Set(values)];
  }

  function sanitizeCaseInsensitiveArray(values) {
    return unique(
      values
        .filter(value => typeof value === 'string')
        .map(value => value.trim().toLowerCase())
        .filter(Boolean)
    );
  }

  function sanitizeSelectors(values) {
    return unique(
      values
        .filter(value => typeof value === 'string')
        .map(value => value.trim())
        .filter(Boolean)
    );
  }

  function cloneDefaultData() {
    return {
      disableTerms: sanitizeCaseInsensitiveArray(DEFAULT_FILTER_DATA.disableTerms),
      aiOverviewPatterns: sanitizeCaseInsensitiveArray(
        DEFAULT_FILTER_DATA.aiOverviewPatterns
      ),
      aiIndicatorPhrases: sanitizeCaseInsensitiveArray(
        DEFAULT_FILTER_DATA.aiIndicatorPhrases
      ),
      lowQualityDomains: sanitizeCaseInsensitiveArray(
        DEFAULT_FILTER_DATA.lowQualityDomains
      ),
      adIndicatorLabels: sanitizeCaseInsensitiveArray(
        DEFAULT_FILTER_DATA.adIndicatorLabels
      ),
      aiSelectors: sanitizeSelectors(DEFAULT_FILTER_DATA.aiSelectors),
      adSelectors: sanitizeSelectors(DEFAULT_FILTER_DATA.adSelectors)
    };
  }

  function getAssetUrl(relativePath) {
    if (
      typeof chrome !== 'undefined' &&
      chrome.runtime &&
      typeof chrome.runtime.getURL === 'function'
    ) {
      return chrome.runtime.getURL(relativePath);
    }

    if (
      typeof browser !== 'undefined' &&
      browser.runtime &&
      typeof browser.runtime.getURL === 'function'
    ) {
      return browser.runtime.getURL(relativePath);
    }

    return null;
  }

  async function loadFilterData() {
    if (filterDataLoaded) {
      return filterData;
    }

    if (filterDataLoadingPromise) {
      return filterDataLoadingPromise;
    }
    filterDataLoadingPromise = (async() => {
      const data = cloneDefaultData();

      const fetchFn =
        typeof globalThis !== 'undefined' && typeof globalThis.fetch === 'function'
          ? globalThis.fetch.bind(globalThis)
          : null;

      if (fetchFn) {
        const entries = Object.entries(DATA_FILE_PATHS);
        await Promise.allSettled(
          entries.map(async([key, path]) => {
            const assetUrl = getAssetUrl(path);
            if (!assetUrl) {
              return;
            }

            try {
              const response = await fetchFn(assetUrl);
              if (!response.ok) {
                Logger.warn(`Failed to load data file ${path}: ${response.status}`);
                return;
              }

              const payload = await response.json();
              if (!Array.isArray(payload)) {
                Logger.warn(`Unexpected data format for ${path}`);
                return;
              }

              const isCaseInsensitiveKey =
                key === 'disableTerms' ||
                key === 'aiOverviewPatterns' ||
                key === 'aiIndicatorPhrases' ||
                key === 'lowQualityDomains' ||
                key === 'adIndicatorLabels';

              if (isCaseInsensitiveKey) {
                data[key] = sanitizeCaseInsensitiveArray(payload);
              } else if (key === 'aiSelectors' || key === 'adSelectors') {
                data[key] = sanitizeSelectors(payload);
              }
            } catch (error) {
              Logger.warn(`Error loading data file ${path}`, error);
            }
          })
        );
      }

      filterData = data;
      filterDataLoaded = true;
      return filterData;
    })();

    try {
      return await filterDataLoadingPromise;
    } finally {
      filterDataLoadingPromise = null;
    }
  }

  function containsAiOverviewHeading(text) {
    if (!text) {
      return false;
    }
    const normalized = text.toLowerCase();
    return filterData.aiOverviewPatterns.some(pattern => normalized.includes(pattern));
  }

  function containsAiIndicator(text) {
    if (!text) {
      return false;
    }
    const normalized = text.toLowerCase();
    return filterData.aiIndicatorPhrases.some(phrase => normalized.includes(phrase));
  }

  function isDomainWhitelisted(hostname) {
    if (!hostname) {
      return false;
    }

    if (!Array.isArray(filterSettings.customWhitelist)) {
      return false;
    }

    const normalized = hostname.toLowerCase();
    return filterSettings.customWhitelist.some(entry => {
      if (typeof entry !== 'string') {
        return false;
      }
      const candidate = entry.trim().toLowerCase();
      if (!candidate) {
        return false;
      }
      return normalized === candidate || normalized.endsWith(`.${candidate}`);
    });
  }

  function isLowQualityHostname(hostname) {
    if (!hostname) {
      return false;
    }

    const normalized = hostname.toLowerCase();
    if (isDomainWhitelisted(normalized)) {
      return false;
    }

    return filterData.lowQualityDomains.some(domain =>
      normalized === domain || normalized.endsWith(`.${domain}`)
    );
  }

  function extractHostname(urlString, depth = 0) {
    if (!urlString || depth > 3) {
      return null;
    }

    try {
      const parsed = new URL(urlString, window.location.origin);
      const hostname = parsed.hostname.toLowerCase();

      if (/(^|\.)google\./i.test(hostname)) {
        const candidateParams = ['url', 'q', 'u', 'target', 'continue'];
        for (const param of candidateParams) {
          const paramValue = parsed.searchParams.get(param);
          if (paramValue) {
            const extracted = extractHostname(paramValue, depth + 1);
            if (extracted) {
              return extracted;
            }
          }
        }
      }

      return hostname;
    } catch {
      return null;
    }
  }

  // Check if we should auto-disable extension based on search query
  function shouldAutoDisable() {
    const urlParams = new URLSearchParams(window.location.search);
    const query = urlParams.get('q');
    if (!query) {
      return false;
    }

    const lowerQuery = query.toLowerCase();
    return filterData.disableTerms.some(term => lowerQuery.includes(term));
  }

  // Show banner when auto-disabled
  function showAutoDisableBanner() {
    const existingBanner = document.getElementById(
      'clean-search-auto-disable-banner'
    );
    if (existingBanner) {
      existingBanner.remove();
    }

    const banner = document.createElement('div');
    banner.id = 'clean-search-auto-disable-banner';
    banner.style.cssText = `
      position: fixed;
      top: 0;
      left: 0;
      right: 0;
      background: linear-gradient(135deg, #ff8c00 0%, #ff6600 100%);
      color: white;
      padding: 12px 20px;
      text-align: center;
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
      font-size: 14px;
      font-weight: 500;
      z-index: 10000;
      cursor: pointer;
      box-shadow: 0 2px 10px rgba(0,0,0,0.2);
      transition: all 0.3s ease;
    `;

    banner.innerHTML = `
       SlopSlurp temporarily disabled - Click to re-enable
      <small style="display: block; margin-top: 4px; opacity: 0.9; font-size: 12px;">
        Auto-disabled because your search might be looking for filtered content
      </small>
    `;

    banner.addEventListener('click', () => {
      extensionEnabled = true;
      banner.remove();
      showNotification('SlopSlurp re-enabled', 'success');
      setTimeout(() => {
        if (filterSettings.minimalistMode) {
          initMinimalistMode();
        } else {
          initComprehensiveMode();
        }
      }, 100);
    });

    document.body.appendChild(banner);
  }

  // Show notification
  function showNotification(message, type = 'info') {
    const notification = document.createElement('div');
    notification.style.cssText = `
      position: fixed;
      top: 20px;
      right: 20px;
      background: ${type === 'success' ? '#10b981' : '#3b82f6'};
      color: white;
      padding: 12px 16px;
      border-radius: 8px;
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
      font-size: 14px;
      z-index: 10001;
      box-shadow: 0 4px 12px rgba(0,0,0,0.2);
      transform: translateX(100%);
      transition: transform 0.3s ease;
    `;

    notification.textContent = message;
    document.body.appendChild(notification);

    setTimeout(() => {
      notification.style.transform = 'translateX(0)';
    }, 100);

    setTimeout(() => {
      notification.style.transform = 'translateX(100%)';
      setTimeout(() => {
        if (notification.parentNode) {
          notification.parentNode.removeChild(notification);
        }
      }, 300);
    }, 3000);
  }

  // Reset stats for new query
  function resetStats() {
    const urlParams = new URLSearchParams(window.location.search);
    const currentQuery = urlParams.get('q');

    if (currentQuery !== lastQuery) {
      lastQuery = currentQuery;
      currentStats = {
        aiElementsRemoved: 0,
        lowQualitySitesRemoved: 0,
        adsRemoved: 0,
        totalElementsRemoved: 0,
        scanCount: 0,
        lastScanTime: Date.now(),
        placeholdersCreated: 0
      };

      if (typeof chrome !== 'undefined' && chrome.storage) {
        chrome.storage.local.set({ cleanSearchStats: currentStats });
      }
    }
  }

  // Update stats
  function updateStats(type, count = 1) {
    currentStats[type] += count;
    currentStats.totalElementsRemoved += count;
    currentStats.lastScanTime = Date.now();

    if (typeof chrome !== 'undefined' && chrome.storage) {
      chrome.storage.local.set({ cleanSearchStats: currentStats });
    }
  }

  function incrementPlaceholdersCreated() {
    currentStats.placeholdersCreated += 1;
    currentStats.lastScanTime = Date.now();

    if (typeof chrome !== 'undefined' && chrome.storage) {
      chrome.storage.local.set({ cleanSearchStats: currentStats });
    }
  }

  // ============ MINIMALIST MODE IMPLEMENTATION ============

  function runMinimalistScan() {
    if (!extensionEnabled) {
      return;
    }

    if (filterSettings.hideAiModeButton) {
      hideAiModeInTopbar();
    }

    const mainBody = document.querySelector('div#rcnt');
    const headings = Array.from(mainBody?.querySelectorAll('h1, h2') || []);
    const aiHeading = headings.find(heading =>
      containsAiOverviewHeading(heading?.innerText || heading?.textContent)
    );

    let aiOverview = aiHeading?.closest('div#rso > div');
    if (!aiOverview) {
      aiOverview = aiHeading?.closest('div#rcnt > div');
    }
    if (aiOverview) {
      removeElement(aiOverview, 'ai');
    }

    const headerTabs = document.querySelector('div#hdtb-sc > div');
    if (headerTabs) {
      headerTabs.style.paddingBottom = '12px';
    }

    const mainElement = document.querySelector('[role="main"]');
    if (mainElement) {
      mainElement.style.marginTop = '24px';
    }

    removePeopleAlsoAskEntries();
  }

  function initMinimalistMode() {
    Logger.info('Starting minimalist mode');

    if (minimalistObserver) {
      minimalistObserver.disconnect();
    }
    if (comprehensiveObserver) {
      comprehensiveObserver.disconnect();
    }

    minimalistObserver = new MutationObserver(() => runMinimalistScan());

    minimalistObserver.observe(document, {
      childList: true,
      subtree: true
    });

    setTimeout(() => {
      minimalistObserver.takeRecords();
      runMinimalistScan();
    }, 100);
  }

  // ============ COMPREHENSIVE MODE IMPLEMENTATION ============

  function isLowQualitySite(result) {
    try {
      const anchorElement = result.querySelector('a');
      if (!anchorElement || !anchorElement.href) {
        return false;
      }
      
      const url = anchorElement.href;
      const hostname = new URL(url).hostname;
      return isLowQualityHostname(hostname);
    } catch {
      return false;
    }
  }

  function removeElement(element, type = 'unknown') {
    if (
      !extensionEnabled ||
      !element ||
      element.hasAttribute('data-removed') ||
      element.hasAttribute('data-clean-search-removed') ||
      safetyCounter >= MAX_REMOVALS_PER_SCAN
    ) {
      return;
    }
    
    // Increment safety counter to prevent excessive removals
    safetyCounter++;

    try {
      if (!element.hasAttribute('data-clean-search-original-display')) {
        let originalDisplay = '';
        try {
          originalDisplay = window.getComputedStyle(element).display || '';
        } catch {
          originalDisplay = '';
        }
        element.setAttribute('data-clean-search-original-display', originalDisplay);
      }

      element.setAttribute('data-clean-search-type', type);
      // Mark element as removed by either system so other code won't try again
      element.setAttribute('data-removed', 'true');
      element.setAttribute('data-clean-search-removed', 'true');
      element.style.display = 'none';

      const statType =
        type === 'ai'
          ? 'aiElementsRemoved'
          : type === 'low-quality'
            ? 'lowQualitySitesRemoved'
            : type === 'ad'
              ? 'adsRemoved'
              : 'totalElementsRemoved';

      updateStats(statType, 1);

      if (filterSettings.showReplacementPlaceholders) {
        createRemovalPlaceholder(element, type);
      }

      // Log the removed DOM node (object) so developers can inspect it when logging is enabled
      Logger.info('Removed element', { type, element });
    } catch (error) {
      Logger.warn(`Error removing ${type} element:`, error);
    }
  }

  function ensurePlaceholderStyles() {
    if (placeholderStylesInjected) {
      return;
    }

    const style = document.createElement('style');
    style.id = 'slopslurp-placeholder-styles';
    style.textContent = `
      .slopslurp-placeholder {
        display: flex;
        align-items: center;
        justify-content: space-between;
        gap: 8px;
        padding: 12px 16px;
        margin: 12px 0;
        border-radius: 10px;
        border: 1px dashed rgba(16, 150, 72, 0.45);
        background: rgba(16, 150, 72, 0.12);
        color: #114d2d;
        cursor: pointer;
        transition: background 0.2s ease, border-color 0.2s ease;
        font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
        font-size: 14px;
        line-height: 1.4;
      }

      .slopslurp-placeholder:hover {
        background: rgba(16, 150, 72, 0.18);
        border-color: rgba(16, 150, 72, 0.6);
      }

      .slopslurp-placeholder:focus {
        outline: 2px solid rgba(16, 150, 72, 0.45);
        outline-offset: 2px;
      }

      .slopslurp-placeholder-label {
        font-weight: 600;
      }

      .slopslurp-placeholder-action {
        display: inline-flex;
        align-items: center;
        gap: 6px;
        font-weight: 600;
        border-radius: 999px;
        padding: 6px 12px;
        background: rgba(17, 77, 45, 0.12);
        border: 1px solid rgba(17, 77, 45, 0.25);
        color: inherit;
        white-space: nowrap;
      }

      .slopslurp-placeholder:hover .slopslurp-placeholder-action {
        background: rgba(17, 77, 45, 0.18);
        border-color: rgba(17, 77, 45, 0.4);
      }

      .slopslurp-restore-dismiss {
        display: inline-flex;
        align-items: center;
        gap: 6px;
        margin: 8px 0;
        padding: 6px 12px;
        border-radius: 999px;
        border: 1px solid rgba(17, 77, 45, 0.3);
        background: rgba(17, 77, 45, 0.1);
        color: #114d2d;
        font-size: 12px;
        font-weight: 600;
        cursor: pointer;
      }

      .slopslurp-restore-dismiss:hover {
        background: rgba(17, 77, 45, 0.14);
      }
    `;

    const target = document.head || document.documentElement;
    if (target) {
      target.appendChild(style);
      placeholderStylesInjected = true;
    }
  }

  function getPlaceholderSummary(type) {
    switch (type) {
    case 'ai':
      return 'SlopSlurp removed an AI-generated answer';
    case 'low-quality':
      return 'SlopSlurp removed a low-quality result';
    case 'ad':
      return 'SlopSlurp removed a sponsored result';
    default:
      return 'SlopSlurp removed a result';
    }
  }

  function createRemovalPlaceholder(element, type) {
    if (!filterSettings.showReplacementPlaceholders) {
      return;
    }

    if (!element || element.hasAttribute('data-clean-search-has-placeholder')) {
      return;
    }

    const parent = element.parentElement;
    if (!parent) {
      return;
    }

    ensurePlaceholderStyles();

    const placeholder = document.createElement('div');
    placeholder.className = 'slopslurp-placeholder';
    placeholder.setAttribute('role', 'button');
    placeholder.setAttribute('tabindex', '0');
    placeholder.setAttribute('data-clean-search-placeholder', 'true');
    placeholder.setAttribute('aria-expanded', 'false');

    const placeholderId = `slopslurp-placeholder-${++placeholderIdCounter}`;
    placeholder.dataset.placeholderId = placeholderId;
    element.setAttribute('data-clean-search-placeholder-id', placeholderId);
    element.setAttribute('data-clean-search-has-placeholder', 'true');

    const summary = getPlaceholderSummary(type);
    const action = 'Click to show temporarily';

    placeholder.innerHTML = `
      <span class="slopslurp-placeholder-label">${summary}</span>
      <span class="slopslurp-placeholder-action">${action}</span>
    `;
    placeholder.setAttribute('aria-label', `${summary}. ${action}.`);

    const activationHandler = event => {
      event.preventDefault();
      handlePlaceholderActivation(placeholder);
    };

    placeholder.addEventListener('click', activationHandler);
    placeholder.addEventListener('keydown', event => {
      if (event.key === 'Enter' || event.key === ' ') {
        event.preventDefault();
        handlePlaceholderActivation(placeholder);
      }
    });

    parent.insertBefore(placeholder, element);

    placeholderEntries.set(placeholder, {
      placeholder,
      element,
      type,
      activationHandler,
      timer: null,
      active: false,
      closeButton: null,
      closeHandler: null
    });

    incrementPlaceholdersCreated();
  }

  function handlePlaceholderActivation(placeholder) {
    const entry = placeholderEntries.get(placeholder);
    if (!entry) {
      return;
    }

    if (entry.active) {
      hideRestoredContent(entry, true);
    } else {
      showRestoredContent(entry);
    }
  }

  function showRestoredContent(entry) {
    const { element, placeholder } = entry;

    if (!element || !placeholder) {
      return;
    }

    placeholder.style.display = 'none';
    placeholder.setAttribute('aria-expanded', 'true');
    entry.active = true;

    let originalDisplay = element.getAttribute('data-clean-search-original-display') || '';
    if (!originalDisplay || originalDisplay === 'none') {
      originalDisplay = '';
    }
    element.style.display = originalDisplay;
    element.setAttribute('data-clean-search-restored', 'true');

    if (entry.timer) {
      clearTimeout(entry.timer);
      entry.timer = null;
    }

    if (typeof PLACEHOLDER_TIMEOUT_MS === 'number' && PLACEHOLDER_TIMEOUT_MS > 0) {
      entry.timer = window.setTimeout(() => hideRestoredContent(entry, false), PLACEHOLDER_TIMEOUT_MS);
    }

    if (!entry.closeButton && element.nodeType === 1) {
      const closeButton = document.createElement('button');
      closeButton.type = 'button';
      closeButton.className = 'slopslurp-restore-dismiss';
      closeButton.textContent = 'Hide removed result';

      const closeHandler = event => {
        event.preventDefault();
        event.stopPropagation();
        hideRestoredContent(entry, true);
      };

      closeButton.addEventListener('click', closeHandler);
      element.insertAdjacentElement('afterbegin', closeButton);

      entry.closeButton = closeButton;
      entry.closeHandler = closeHandler;
    }
  }

  function hideRestoredContent(entry, focusPlaceholder) {
    const { element, placeholder } = entry;
    if (!element || !placeholder) {
      return;
    }

    if (entry.timer) {
      clearTimeout(entry.timer);
      entry.timer = null;
    }

    if (entry.closeButton && entry.closeHandler) {
      entry.closeButton.removeEventListener('click', entry.closeHandler);
      if (entry.closeButton.parentNode) {
        entry.closeButton.parentNode.removeChild(entry.closeButton);
      }
      entry.closeButton = null;
      entry.closeHandler = null;
    }

    element.style.display = 'none';
    element.removeAttribute('data-clean-search-restored');

    placeholder.style.display = '';
    placeholder.setAttribute('aria-expanded', 'false');
    entry.active = false;

    if (focusPlaceholder && typeof placeholder.focus === 'function') {
      placeholder.focus({ preventScroll: true });
    }
  }

  function removeAllPlaceholders() {
    const placeholders = Array.from(placeholderEntries.keys());
    placeholders.forEach(placeholder => {
      const entry = placeholderEntries.get(placeholder);
      if (!entry) {
        return;
      }

      if (entry.timer) {
        clearTimeout(entry.timer);
        entry.timer = null;
      }

      if (entry.closeButton && entry.closeHandler) {
        entry.closeButton.removeEventListener('click', entry.closeHandler);
        if (entry.closeButton.parentNode) {
          entry.closeButton.parentNode.removeChild(entry.closeButton);
        }
        entry.closeButton = null;
        entry.closeHandler = null;
      }

      if (entry.element) {
        entry.element.style.display = 'none';
        entry.element.removeAttribute('data-clean-search-restored');
        entry.element.removeAttribute('data-clean-search-has-placeholder');
        entry.element.removeAttribute('data-clean-search-placeholder-id');
      }

      if (placeholder.parentNode) {
        placeholder.parentNode.removeChild(placeholder);
      }

      entry.active = false;
      placeholderEntries.delete(placeholder);
    });

    placeholderEntries.clear();
  }

  function applyPlaceholdersToRemovedContent() {
    const removedElements = document.querySelectorAll('[data-clean-search-removed]');
    removedElements.forEach(element => {
      const type = element.getAttribute('data-clean-search-type') || 'unknown';
      createRemovalPlaceholder(element, type);
    });
  }

  function handlePlaceholderSettingChange(enabled) {
    if (enabled) {
      ensurePlaceholderStyles();
      applyPlaceholdersToRemovedContent();
    } else {
      removeAllPlaceholders();
    }
  }

  // Safety mechanism to prevent excessive removal
  let safetyCounter = 0;
  const MAX_REMOVALS_PER_SCAN = 25;

  // Function to hide the AI Mode button in the topbar
  function hideAiModeInTopbar() {
    if (!extensionEnabled || !filterSettings.hideAiModeButton) {
      return;
    }

    try {
      // Select the AI Mode button in the topbar
      // Based on its position as the first item or by text content
      const aiModeButtons = Array.from(document.querySelectorAll('div[role="listitem"] a')).filter(a => {
        const text = a.textContent.toLowerCase();
        return text.includes('ai mode');
      });

      aiModeButtons.forEach(button => {
        const listItem = button.closest('div[role="listitem"]');
        if (listItem && !listItem.hasAttribute('data-removed')) {
          listItem.style.display = 'none';
          listItem.setAttribute('data-removed', 'true');
          Logger.debug('Hidden AI Mode button in topbar');
        }
      });
    } catch (error) {
      Logger.error('Error hiding AI Mode button:', error);
    }
  }

  function scanForContent() {
    if (!extensionEnabled) {
      return;
    }

    try {
      currentStats.scanCount++;
      // Reset safety counter for this scan
      safetyCounter = 0;
      runMinimalistScan();

      if (filterSettings.minimalistMode) {
        return;
      }

      if (filterSettings.removeAiOverview) {
        removeAiBlocksBySelector();
        removeAiBlocksByHeadings();
        removeAiResultsByContent();
      }

      if (filterSettings.removeLowQualitySites) {
        removeLowQualityResults();
      }

      if (filterSettings.removeAds) {
        removeAdvertisements();
      }
    } catch (error) {
      Logger.error('Error scanning for content', error);
    }
  }

  function removeAiBlocksBySelector() {
    filterData.aiSelectors.forEach(selector => {
      try {
        const elements = document.querySelectorAll(selector);
        elements.forEach(element => {
          if (element.hasAttribute('data-removed')) {
            return;
          }
          const text = element.textContent || '';
          if (containsAiOverviewHeading(text) || containsAiIndicator(text)) {
            Logger.debug('Found AI element with selector', { selector });
            removeElement(element, 'ai');
          }
        });
      } catch (error) {
        Logger.error('Error with selector ' + selector, error);
      }
    });
  }

  function removePeopleAlsoAskEntries() {
    const questionPairs = document.querySelectorAll('div.related-question-pair');

    questionPairs.forEach(pair => {
      if (!pair || pair.hasAttribute('data-clean-search-removed')) {
        return;
      }

      const container =
        pair.closest('.wQiwMc') ||
        pair.closest('.g') ||
        pair.closest('[data-ved]') ||
        pair.closest('[data-hveid]') ||
        pair;

      if (!container || container.hasAttribute('data-clean-search-removed')) {
        return;
      }

      const textParts = [
        pair.getAttribute('data-q'),
        pair.getAttribute('data-lk'),
        pair.textContent
      ].filter(Boolean);

      const snippetText = collectSnippetText(container);
      if (snippetText) {
        textParts.push(snippetText);
      }

      const combinedText = textParts
        .join(' ')
        .toLowerCase();

      const hasSgeAttribution = Array.from(
        container.querySelectorAll('[data-attrid]')
      ).some(node => {
        const attrId = node.getAttribute('data-attrid');
        return Boolean(attrId && attrId.toLowerCase().includes('sge'));
      });

      let hasLowQualityLink = false;
      const links = container.querySelectorAll('a[href^="http"]');
      links.forEach(link => {
        if (hasLowQualityLink) {
          return;
        }

        try {
          const hostname = extractHostname(link.href);
          if (isLowQualityHostname(hostname)) {
            hasLowQualityLink = true;
          }
        } catch {
          // Ignore malformed URLs
        }
      });

      if (!hasLowQualityLink) {
        const attributionNodes = container.querySelectorAll('[data-fburl]');
        attributionNodes.forEach(node => {
          if (hasLowQualityLink) {
            return;
          }

          const fburl = node.getAttribute('data-fburl');
          if (!fburl) {
            return;
          }

          try {
            const hostname = extractHostname(fburl);
            if (isLowQualityHostname(hostname)) {
              hasLowQualityLink = true;
            }
          } catch {
            // Ignore malformed URLs
          }
        });
      }

      const hasAiSignals =
        hasSgeAttribution ||
        containsAiIndicator(combinedText) ||
        containsAiOverviewHeading(combinedText);

      if (hasAiSignals || hasLowQualityLink) {
        const removalType = hasLowQualityLink ? 'low-quality' : 'ai';
        removeElement(container, removalType);
      }
    });
  }

  function removeAiBlocksByHeadings() {
    const headings = document.querySelectorAll('h1, h2, h3');
    headings.forEach(heading => {
      const text = (heading.textContent || '').toLowerCase().trim();
      if (!text) {
        return;
      }

      if (!containsAiIndicator(text) && !containsAiOverviewHeading(text)) {
        return;
      }

      const containers = [
        heading.closest('.g, .yf, [data-ved]'),
        heading.closest('[data-hveid]'),
        heading.closest('div[jscontroller]'),
        heading.closest('g-section-with-header'),
        heading.closest('div.cUnQKe'),
        heading.parentElement?.parentElement?.parentElement
      ];

      const container = containers.find(el => el && !el.hasAttribute('data-removed'));
      if (container) {
        Logger.debug('Found AI content via heading detection', { text });
        removeElement(container, 'ai');
      }
    });
  }

  function removeAiResultsByContent() {
    const searchResults = document.querySelectorAll('.g, [data-sokoban-feature]');
    searchResults.forEach(result => {
      if (result.hasAttribute('data-removed')) {
        return;
      }

      const headingText = (result.querySelector('h3')?.innerText || '').toLowerCase();
      const descriptionText = collectSnippetText(result).toLowerCase();
      const ariaLabel = (result.getAttribute('aria-label') || '').toLowerCase();

      if (
        containsAiIndicator(headingText) ||
        containsAiIndicator(descriptionText) ||
        containsAiIndicator(ariaLabel)
      ) {
        Logger.debug('Found AI content via result analysis');
        removeElement(result, 'ai');
      }
    });
  }

  function collectSnippetText(result) {
    const snippetSelectors = [
      '.VwiC3b',
      '.yDYNvb',
      '.WKr5lb',
      '.kno-rdesc',
      '.MUxGbd',
      '.LGOjhe',
      '.hgKElc',
      '[data-content-feature]',
      '[data-sncf]'
    ];

    const snippets = [];
    snippetSelectors.forEach(selector => {
      const nodes = result.querySelectorAll(selector);
      nodes.forEach(node => {
        const text = node.textContent || '';
        if (text) {
          snippets.push(text);
        }
      });
    });

    if (!snippets.length) {
      const fallback = result.querySelector('div[data-attrid]');
      if (fallback && fallback.textContent) {
        snippets.push(fallback.textContent);
      }
    }

    return snippets.join(' ');
  }

  function removeLowQualityResults() {
    const searchResults = document.querySelectorAll('.g');
    searchResults.forEach(result => {
      if (!result.hasAttribute('data-removed') && isLowQualitySite(result)) {
        removeElement(result, 'low-quality');
      }
    });
  }

  function removeAdvertisements() {
    try {
      filterData.adSelectors.forEach(selector => {
        try {
          const elements = document.querySelectorAll(selector);
          elements.forEach(element => {
            const container = findAdContainer(element);
            if (container) {
              removeElement(container, 'ad');
            }
          });
        } catch (error) {
          Logger.error('Error with ad selector ' + selector, error);
        }
      });

      const adIndicators = document.querySelectorAll('.g, [data-text-ad], [data-sokoban-feature]');
      adIndicators.forEach(result => {
        if (result.hasAttribute('data-removed')) {
          return;
        }

        const combinedText = [
          result.querySelector('h3')?.innerText || '',
          collectSnippetText(result),
          result.getAttribute('aria-label') || ''
        ]
          .join(' ')
          .toLowerCase();

        const matches = filterData.adIndicatorLabels.some(label =>
          combinedText.includes(label)
        );

        if (matches) {
          const container = findAdContainer(result);
          removeElement(container, 'ad');
        }
      });
    } catch (error) {
      Logger.error('Error removing advertisements', error);
    }
  }

  function findAdContainer(element) {
    for (const selector of filterData.adSelectors) {
      const match = element.closest(selector);
      if (match && !match.hasAttribute('data-removed')) {
        return match;
      }
    }

    const fallback =
      element.closest('.g') ||
      element.closest('[data-ved]') ||
      element.closest('[role="complementary"]') ||
      element.closest('div[jscontroller]');

    if (fallback && !fallback.hasAttribute('data-removed')) {
      return fallback;
    }

    return element;
  }

  function initComprehensiveMode() {
    Logger.info('Starting comprehensive mode');

    // Disconnect any existing observers
    if (minimalistObserver) {
      minimalistObserver.disconnect();
    }
    if (comprehensiveObserver) {
      comprehensiveObserver.disconnect();
    }

    comprehensiveObserver = new MutationObserver(() => {
      if (extensionEnabled && !filterSettings.minimalistMode) {
        setTimeout(() => scanForContent(), 150);
      }
    });

    comprehensiveObserver.observe(document.body || document.documentElement, {
      childList: true,
      subtree: true
    });

    // Initial scans
    scanForContent();
    // Additional scan specifically for the AI Mode button to catch it after page loads
    setTimeout(() => {
      if (filterSettings.hideAiModeButton) {
        hideAiModeInTopbar();
      }
      scanForContent();
    }, 500);
    setTimeout(() => scanForContent(), 2000);
  }

  // ============ INITIALIZATION ============

  function initialize() {
    const start = async() => {
      try {
        await loadFilterData();
        if (loggingEnabled) {
          Logger.info('Filter data loaded', filterData);
        }
        if (shouldAutoDisable()) {
          extensionEnabled = false;
          showAutoDisableBanner();
          Logger.info('Extension auto-disabled due to query content');
          return;
        }

        resetStats();

        const applySettings = () => {
          handlePlaceholderSettingChange(
            extensionEnabled && !!filterSettings.showReplacementPlaceholders
          );

          if (!extensionEnabled) {
            return;
          }

          if (filterSettings.minimalistMode) {
            initMinimalistMode();
          } else {
            initComprehensiveMode();
          }
        };

        if (typeof chrome !== 'undefined' && chrome.storage) {
          chrome.storage.local.get(
            ['cleanSearchEnabled', 'filterSettings', 'loggingEnabled'],
            result => {
              if (result.cleanSearchEnabled !== undefined) {
                extensionEnabled = result.cleanSearchEnabled && extensionEnabled;
              }
              if (result.filterSettings) {
                filterSettings = { ...filterSettings, ...result.filterSettings };
              }

              if (typeof result.loggingEnabled !== 'undefined') {
                loggingEnabled = !!result.loggingEnabled;
              }

              applySettings();
            }
          );
        } else {
          applySettings();
        }

        Logger.info('SlopSlurp initialized', {
          url: window.location.href,
          mode: filterSettings.minimalistMode ? 'minimalist' : 'comprehensive',
          enabled: extensionEnabled
        });

        window.cleanSearchDebug = {
          scan: () => {
            if (filterSettings.minimalistMode) {
              runMinimalistScan();
            } else {
              scanForContent();
            }
          },
          getStats: () => currentStats,
          resetStats: () => {
            currentStats = {
              aiElementsRemoved: 0,
              lowQualitySitesRemoved: 0,
              adsRemoved: 0,
              totalElementsRemoved: 0,
              scanCount: 0,
              lastScanTime: Date.now(),
              placeholdersCreated: 0
            };
            if (typeof chrome !== 'undefined' && chrome.storage) {
              chrome.storage.local.set({ cleanSearchStats: currentStats });
            }
          },
          setEnabled: enabled => {
            extensionEnabled = enabled;
            if (typeof chrome !== 'undefined' && chrome.storage) {
              chrome.storage.local.set({ cleanSearchEnabled: enabled });
            }
            if (enabled) {
              handlePlaceholderSettingChange(
                !!filterSettings.showReplacementPlaceholders
              );
              if (filterSettings.minimalistMode) {
                initMinimalistMode();
              } else {
                initComprehensiveMode();
              }
            } else {
              removeAllPlaceholders();
              if (minimalistObserver) {
                minimalistObserver.disconnect();
              }
              if (comprehensiveObserver) {
                comprehensiveObserver.disconnect();
              }
            }
          },
          updateSettings: newSettings => {
            const oldMinimalistMode = filterSettings.minimalistMode;
            filterSettings = { ...filterSettings, ...newSettings };

            if (newSettings && typeof newSettings.loggingEnabled !== 'undefined') {
              loggingEnabled = !!newSettings.loggingEnabled;
            }

            if (
              newSettings &&
              Object.prototype.hasOwnProperty.call(
                newSettings,
                'showReplacementPlaceholders'
              )
            ) {
              handlePlaceholderSettingChange(
                !!filterSettings.showReplacementPlaceholders
              );
            }

            if (oldMinimalistMode !== filterSettings.minimalistMode) {
              if (filterSettings.minimalistMode) {
                initMinimalistMode();
                showNotification('Switched to minimalist mode', 'success');
              } else {
                initComprehensiveMode();
                showNotification('Switched to comprehensive mode', 'success');
              }
            }

            if (typeof chrome !== 'undefined' && chrome.storage) {
              chrome.storage.local.set({ filterSettings: filterSettings });
            }
          },
          getSettings: () => filterSettings,
          isEnabled: () => extensionEnabled,
          getMode: () => (filterSettings.minimalistMode ? 'minimalist' : 'comprehensive'),
          setLogging: enabled => {
            loggingEnabled = !!enabled;
            if (typeof chrome !== 'undefined' && chrome.storage) {
              chrome.storage.local.set({ loggingEnabled: loggingEnabled });
            }
            if (loggingEnabled) {
              Logger.info('Logging enabled');
            } else {
              console.log('[SlopSlurp] Logging disabled');
            }
          },
          getLogging: () => loggingEnabled,
          switchMode: () => {
            filterSettings.minimalistMode = !filterSettings.minimalistMode;
            window.cleanSearchDebug.updateSettings(filterSettings);
            return filterSettings.minimalistMode ? 'minimalist' : 'comprehensive';
          },

          // Test helper function to help debug with feudalism.html test file
          runDiagnostics: () => {
            Logger.info('Running diagnostics...');
            loggingEnabled = true;

            const aiElements = {};
            filterData.aiSelectors.forEach(selector => {
              try {
                const elements = document.querySelectorAll(selector);
                aiElements[selector] = elements.length;
                Logger.info(`Selector ${selector} matches ${elements.length} elements`);
              } catch (e) {
                Logger.error(`Error with selector ${selector}:`, e);
              }
            });

            Logger.info('Checking for AI mode button in topbar');
            const aiModeButtons = Array.from(
              document.querySelectorAll('div[role="listitem"] a')
            ).filter(a => {
              const text = a.textContent.toLowerCase();
              return text.includes('ai mode');
            });
            Logger.info(`Found ${aiModeButtons.length} AI mode buttons`);

            return {
              aiElements,
              aiModeButtons: aiModeButtons.length,
              settings: filterSettings,
              stats: currentStats
            };
          }
        };

        // Legacy compatibility
        window.debugAiRemover = window.cleanSearchDebug;
      } catch (error) {
        Logger.error('Failed to initialize SlopSlurp', error);
      }
    };

    start();
  }

  // Start initialization when DOM is ready
  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', initialize);
  } else {
    // Initialize on script load
    initialize();
  }
})();
